# Generated by Django 2.1.1 on 2018-09-28 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_delete_usertype'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinfo',
            table='t_user_info',
        ),
    ]
